version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mojeda
      ME_CONFIG_BASICAUTH_PASSWORD: 8521
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB!
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB!
    ports:
      - "27017:27017"
    volumes:
      - /home/mateus/dev/nodejs_micro/data:/data/db
    networks:
      - mongo-compose-network
    restart: always

networks: 
    mongo-compose-network:
      driver: bridge